ratings = {'hamilton': 8,\
            'verstappen': 2,\
            'russell': 9,\
            'leclerc': 1,\
            'perez': 4,\
            'sainz': 3,\
            'norris': 14,\
            'ricciardo': 15,\
            'gasly': 10,\
            'alonso': 5,\
            'ocon': 7,\
            'vettel': 16,\
            'stroll': 18,\
            'bottas': 12,\
            'tsunoda': 13,\
            'zhou': 17,\
            'albon': 19,\
            'latifi': 20,\
            'schumacher': 11,\
            'magnussen': 6}