ratings = {'hamilton': 2,\
            'verstappen': 1,\
            'russell': 3,\
            'leclerc': 5,\
            'perez': 4,\
            'sainz': 6,\
            'norris': 9,\
            'ricciardo': 10,\
            'gasly': 14,\
            'alonso': 7,\
            'ocon': 8,\
            'vettel': 13,\
            'stroll': 16,\
            'bottas': 11,\
            'tsunoda': 19,\
            'zhou': 12,\
            'albon': 17,\
            'latifi': 20,\
            'schumacher': 18,\
            'magnussen': 15}